algoritmo "semnome"
//Desafio
//6. Fazer um programa para apresentar a divisão de dois números reais.
//Entrada :
//A entrada contém 2 valores reais.
//Saída:
//Resultado da divisão
var

   num1, num2 : real
   divisao : real
   

inicio
   escreval ("Digite um número:")
   leia(num1)
   escreval("Digite outro número:")
   leia(num2)
   
   divisao <- num1 / num2
   
   escreval(" O resultado da divisao é: ", divisao)




fimalgoritmo